spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: iclyj-auth
          uri: lb://iclyj-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        # 系统模块
        - id: iclyj-system
          uri: lb://iclyj-system
          predicates:
            - Path=/system/**
          filters:
#          - name: Hystrix
#            args:
#              name: fallback
#              fallbackUri: forward:/fallback
            - StripPrefix=1
        # 系统测试模块
        - id: iclyj-system-test
          uri: lb://iclyj-system-test
          predicates:
            - Path=/system-test/**
          filters:
            - StripPrefix=1


# 不校验验证码终端(swagger认证的client_id)
ignore:
  clients:
    - iclyj